//Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created on        : 2019-12-24T14:23:55.002+05:30
// created by        :
// generated by      : Administrator
// generated from    : C:\Users\Administrator\Documents\github\git_test\proj2\juyhg\skfjzlkx.idsng
// IDesignSpec rev   : idsbatch v 6.16.4.7

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 8
// C++ Types int              : hwint
// Bus Type                   : PROPRIETARY
// BigEndian                  : false
// LittleEndian               : false
// Dist. Decode and Readback  : false
//---------------------------------------------------------------------------------------------------------------
/*----------------------------------------------------------------------
Class       : skfjzlkx_reha
-----------------------------------------------------------------------*/

`ifndef CLASS_skfjzlkx_reha
`define CLASS_skfjzlkx_reha
class skfjzlkx_reha extends uvm_reg;
    `uvm_object_utils(skfjzlkx_reha)

    /*knfmk.d,.s*/
    rand uvm_reg_field hha;

    /*:Lfiuldkh*/
    rand uvm_reg_field uywhkjk;

    // Function : new
    function new(string name = "skfjzlkx_reha");
        super.new(name, 32, build_coverage(UVM_NO_COVERAGE));
        add_coverage(build_coverage(UVM_NO_COVERAGE));            //Added because build coverage in the line above doesn’t work due to a bug in UVM 1.1 library

    endfunction

    // Function : build
    virtual function void build();
        this.hha = uvm_reg_field::type_id::create("hha");

        this.uywhkjk = uvm_reg_field::type_id::create("uywhkjk");

        this.hha.configure(this, 16,  16, "RW", 0, 16'd0, 1, 1, 0);
        this.uywhkjk.configure(this, 16,  0, "WC", 0, 16'd0, 1, 1, 0);

    endfunction
endclass
`endif

/*----------------------------------------------------------------------
Class      : skfjzlkx_block
-----------------------------------------------------------------------*/
`ifndef CLASS_skfjzlkx_block
`define CLASS_skfjzlkx_block
class skfjzlkx_block extends uvm_reg_block;
    `uvm_object_utils(skfjzlkx_block)

    rand skfjzlkx_reha reha;

    // Function : new
    function new(string name = "skfjzlkx_block");
        super.new(name, UVM_NO_COVERAGE);
    endfunction

    // Function : build
    virtual function void build();
        //REHA
        reha   =   skfjzlkx_reha::type_id::create("reha");
        reha.configure(this, null, "reha");
        reha.build();

        //define default map and add reg/regfiles
        default_map= create_map("default_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
        default_map.add_reg(reha, 'h0, "RW");

        lock_model();
    endfunction

endclass : skfjzlkx_block
`endif
