//Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created by        : 
// generated by      : Agnisys
// generated from    : D:\AgnisysProjects\git_test\Allegro_test\Merger\merg4.idsng
// IDesignSpec rev   : idsbatch v4.16.26.2

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 8
// C++ Types int              : hwint
// Bus Type                   : AXI
// BigEndian                  : false
// LittleEndian               : false
// Dist. Decode and Readback  : false
//--------------------------------------------------------------------------------------------------------------- 



`include "merg45_if.sv"

`include "merg4.v"


`include "axi_if.sv"

module merg45_ids_wrapper
    #(
    //  PARAMETERS
    parameter bus_width   = 8,
    parameter addr_width  = 12,
    
    parameter block_offset   = 'h0,
    parameter merg45_address_width = addr_width
    )
    (
    
    merg45_reggroupname_regname2_interface.mp   merg45_reggroupname_regname2_if,
    merg45_regnam_interface.mp   merg45_regnam_if,
    axi_if.axi_mp  merg45_axi_if
    
    
    );
    // Module Instantiation
    
    merg45_ids  merg45ids (
    
    //merg45_ids
    
    .regnam_enb(merg45_regnam_if.regnam_enb),
    .regnam_ff_r (merg45_regnam_if.regnam_ff_r),
    .regnam_fxy_r (merg45_regnam_if.regnam_fxy_r),
    .regnam_fx1_r (merg45_regnam_if.regnam_fx1_r),
    
    .reggroupname_regname2_enb(merg45_reggroupname_regname2_if.reggroupname_regname2_enb),
    .reggroupname_regname2_f12_r (merg45_reggroupname_regname2_if.reggroupname_regname2_f12_r),
    .reggroupname_regname2_f1_r (merg45_reggroupname_regname2_if.reggroupname_regname2_f1_r),
    .reggroupname_regname2_f13_r (merg45_reggroupname_regname2_if.reggroupname_regname2_f13_r),
    .reggroupname_regname2_f11_r (merg45_reggroupname_regname2_if.reggroupname_regname2_f11_r),
    
    //AXI signals
    
    .aclk(merg45_axi_if.aclk),
    .aresetn(merg45_axi_if.aresetn),
    .awaddr(merg45_axi_if.awaddr),
    .awvalid(merg45_axi_if.awvalid),
    .awready(merg45_axi_if.awready),
    .awprot(merg45_axi_if.awprot),
    .wdata(merg45_axi_if.wdata),
    .wvalid(merg45_axi_if.wvalid),
    .wready(merg45_axi_if.wready),
    .wstrb(merg45_axi_if.wstrb),
    .bresp(merg45_axi_if.bresp),
    .bready(merg45_axi_if.bready),
    .bvalid(merg45_axi_if.bvalid),
    .araddr(merg45_axi_if.araddr),
    .arvalid(merg45_axi_if.arvalid),
    .arready(merg45_axi_if.arready),
    .arprot(merg45_axi_if.arprot),
    .rdata(merg45_axi_if.rdata),
    .rvalid(merg45_axi_if.rvalid),
    .rready(merg45_axi_if.rready),
    .rresp(merg45_axi_if.rresp)
    );
    
    // Instantiation End
    
endmodule

