include makefileseq
UVM_SRC = ${UVM_HOME}/src
UVM_FILES = $(UVM_SRC)/uvm.sv

UVM_VERBOSITY =	UVM_HIGH

	
##########
run: compile seq merge ivs

compile: 
		test -e work ||vlib work
	vlog -incr +incdir+$(UVM_SRC) $(UVM_FILES) +define+UVM_NO_DEPRECATED
	vlog -incr -novopt +cover="sbeft" +libext+.v $(COMMON) +incdir+=../ $(DESIGN) 
	vlog -incr -suppress 2223 -suppress 2181 $(INCDIRS) $(FILES) $(DEFINE_FLAGS)

seq: $(RUN_SEQ)

uvm_%_seq: 
 
ifeq ($(GUI),1)
	vsim +UVM_VERBOSITY=$(UVM_VERBOSITY) -novopt -coverage -voptargs="+cover=bestf" -sv_lib ${UVM_HOME}/lib/uvm_dpi -novopt top -do "add wave -r sim:/top/*;run -all;exit" +UVM_SEQUENCE=$@
else
	vsim +UVM_VERBOSITY=$(UVM_VERBOSITY) -novopt -c -coverage -voptargs="+cover=bestf" -sv_lib ${UVM_HOME}/lib/uvm_dpi -novopt top -do "coverage save -testname $@ -onexit $@.ucdb; run -all;exit" +UVM_SEQUENCE=$@ |tee $@.txt 
endif

NEG_uvm_%_seq:

ifeq ($(GUI),1)
	vsim -sv_lib ${UVM_HOME}/lib/uvm_dpi -novopt top -do "add wave -r sim:/top/*;run -all;exit" +UVM_SEQUENCE=$@
else
	vsim +UVM_VERBOSITY=$(UVM_VERBOSITY) -novopt -c -nocvg -sv_lib ${UVM_HOME}/lib/uvm_dpi -novopt top -do "coverage save -testname $@ -onexit $@.ucdb; run -all;exit" +UVM_SEQUENCE=$@ |tee $@.txt
endif


clean_text_files:
	rm -rf text_files/*report*

clean:  clean_text_files
	rm -rf  *.tmp  *.log  log transcript work *.wlf vsim.fcdb *.vstf \
	rm -rf *~ core csrc simv* vc_hdrs.h ucli.key urg* *.log core.* *.ucdb uvm_arv_main_seq.ucdb *.xml *main_seq.txt

distclean:
	@echo "Cleaning up files..."
	find . -name '*.vcd' -exec rm -f {} \; ; \
	find . -name 'core' -exec rm -f {} \; ; \
	find . -name '.cwr*' -exec rm -f {} \; ; \
	find . -name 'transcript' -exec rm -f {} \; ; \
	find . -name 'work*' -exec rm -rf {} \; ; \
	find . -name 'vsim.wlf' -exec rm -f {} \; ; \
	find . -name '*.vstf' -exec rm -f {} \; ; \
	find . -name 'simv*' -exec rm -rf {} \; ; \
	find . -name 'urg*' -exec rm -rf {} \; ; \
	find . -name 'c_hdrs.h' -exec rm -rf {} \; ; \
	find . -name 'ucli.key' -exec rm -rf {} \; ; \
	find . -name 'assert.report' -exec rm -f {} \; ; \
	find . -name 'csrc' -exec rm -rf {} \; ; \
	find . -name '*.log' -exec rm -f {} \; ; \
	find . -name '*.bak' -exec rm -f {} \; ; 
        

merge:
	vcover merge uvm_arv_main_seq.ucdb *.ucdb

ivs:
	./script/ivs.tcl -in uvm_arv_main_seq.ucdb
	idsbatch $(PLAN) -result uvm_arv_main_seq_ivs.xml -out "ivs_html ivs_graph" -dir arvreport