##########################################################################################

#####    NOTE:--- UVM_HOME should point to the files provided by cadence -----

##########################################################################################

include makefileseq

UVM_SRC = ${UVM_HOME}/src
UVM_FILES = $(UVM_SRC)/uvm.sv

UVM_VERBOSITY =	UVM_HIGH
	
##########
run: clean compile seq ivs

compile: 
	irun $(DESIGN) +define+UVM_NO_DEPRECATED  
	
seq: $(RUN_SEQ)

uvm_%_seq: 

ifeq ($(GUI),1)
	$(IUS) $(SIM) -gui -run |tee $@.txt
else
	$(IUS) $(SIM) |tee $@.txt
endif

NEG_uvm_%_seq: 

ifeq ($(GUI),1)
	$(IUS_NEG) $(SIM) -gui -run |tee $@.txt
else
	$(IUS_NEG) $(SIM) |tee $@.txt
endif
	
IUS = irun -access +rwc  -covtest $@ -coverage all -uvmhome $(UVM_HOME) +UVM_VERBOSITY=$(UVM_VERBOSITY) -verbose -quiet 
IUS_NEG = irun -access +rwc -covtest $@ -coverage all -uvmhome $(UVM_HOME) +UVM_VERBOSITY=$(UVM_VERBOSITY) -verbose -quiet 

	
SIM = -define INCA $(DEFINE_FLAGS) -timescale "1ns/1ns" $(INCDIRS) $(DESIGN) $(FILES) +UVM_SEQUENCE=$@ 


CHECK = \
	@$(TEST) \( `grep -c 'UVM_ERROR :    $(N_ERRS)' irun.log` -eq 1 \) -a \
		 \( `grep -c 'UVM_FATAL :    $(N_FATALS)' irun.log` -eq 1 \)
	
clean:  
	rm -rf *~ core csrc simv* *.xml *_seq.txt vc_hdrs.h ucli.key *.log html_*  
	rm -rf cov_work iccr.key ies.vsof imc.key INCA_libs irun.key imc.cmd ivs_*

ivs: 
	 touch imc.cmd
	 chmod 777 imc.cmd
	 echo " merge cov_work/scope/* -overwrite -out all" > imc.cmd 
	 imc -exec imc.cmd
	 ./script/ivs.tcl -in cov_work/scope/all/ -imc
	idsbatch $(PLAN_CADENCE) -result all_ivs.xml -out "ivs_html ivs_graph" -dir arvreport
