include makefileseq
# UVM_HOME=/auto/cae/cadence/XCELIUM1704/tools/methodology/UVM/CDNS-1.1d/sv       uncomment it for internal use:-Anmol
UVM_SRC = ${UVM_HOME}/src
UVM_FILES = $(UVM_SRC)/uvm.sv

UVM_VERBOSITY =	UVM_HIGH
	
##########
run: compile seq xrun

compile: 
	xrun $(DESIGN) +define+UVM_NO_DEPRECATED  
	
seq: $(RUN_SEQ)

uvm_%_seq: 

ifeq ($(GUI),1)
	$(XRUN) $(SIM) -gui -run |tee $@.txt
else
	$(XRUN) $(SIM) |tee $@.txt
endif

NEG_uvm_%_seq: 

ifeq ($(GUI),1)
	$(XRUN_NEG) $(SIM) -gui -run |tee $@.txt
else
	$(XRUN_NEG) $(SIM) |tee $@.txt
endif
	
XRUN = xrun -access +rwc -covoverwrite -coverage all -uvmhome $(UVM_HOME) +UVM_VERBOSITY=$(UVM_VERBOSITY) -verbose -quiet 
XRUN_NEG = xrun -access +rwc -covtest test1 -covoverwrite -coverage Block:Expr:Toggle:Fsm -uvmhome $(UVM_HOME) +UVM_VERBOSITY=$(UVM_VERBOSITY) -verbose -quiet 

	
SIM = -define INCA $(DEFINE_FLAGS) -timescale "1ns/1ns" $(INCDIRS) $(DESIGN) $(FILES) +UVM_SEQUENCE=$@ 


CHECK = \
	@$(TEST) \( `grep -c 'UVM_ERROR :    $(N_ERRS)' xrun.log` -eq 1 \) -a \
		 \( `grep -c 'UVM_FATAL :    $(N_FATALS)' xrun.log` -eq 1 \)
	
clean:  
	rm -rf *~ core csrc simv* *.xml *_main_seq.txt vc_hdrs.h ucli.key *.log html_* 
	rm -rf cov_work iccr.key ies.vsof imc.key INCA_libs xrun.key xrun.history imc.cmd xcelium.d arvreport ivs_*

xrun: 
	 echo "merge -out all cov_work/scope/test/ cov_work/scope/test1/ -initial_model test -metrics all -overwrite -message 1" > imc.cmd 
	 imc -exec imc.cmd
	./script/ivs.tcl -in cov_work/scope/all/ -imc
	idsbatch $(PLAN_CADENCE) -result all_ivs.xml -out "ivs_html ivs_graph" -dir arvreport
