/* Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****

*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
created by          :
generated by        : Agnisys71
IDesignSpec ver     :  7.12.0.0

**** This code is generated with the following settings ***
Reg Width                  : 32
Address Unit               : 8
C++ Types int              : hwint
Bus Type                   : CUSTOM
BigEndian                  : false
LittleEndian               : true
Dist. Decode and Readback  : false
------------------------------------------------------------ */

`ifndef SAMPLE_TOP_BLOCK_REGMEM
`define SAMPLE_TOP_BLOCK_REGMEM

package sample_top_block_regmem_pkg;
    import uvm_pkg::*;
    `include "uvm_macros.svh"

    `include "Test201 - Copy.regmem.sv"
endpackage
`endif
