/* Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****

*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
created by          :
generated by        : Saurabh
IDesignSpec rev     :  6.16.4.7

**** This code is generated with the following settings ***
Reg Width                  : 32
Address Unit               : 8
C++ Types int              : hwint
Bus Type                   :
BigEndian                  : false
LittleEndian               : false
Dist. Decode and Readback  : false
------------------------------------------------------------ */


arg  =  2;

Status_EEPROM ( arg );

pack  =  10;
chik  =  12;

Shadow_EEPROM ( pack,chik );
