//=====================================================================================================================
//All Rights Reserved. *************Agnisys**************** fadfasdfsdfsd
//*** This file is auto generated by ISequenceSpec (http://www.agnisys.com) . Please do not edit this file. ***
//Created by        :
//Generated by      :  Saurabh
//Generated from    :  C:\Users\Anupam\Documents\GitHub\git_test\Allegro_test\test99\sample_sequence.idsng
//IDesignSpec rev   :  idsbatch v 6.16.4.7
//=====================================================================================================================

#define  REG_READ(ADDR) (*(volatile hwint32*) (ADDR))

#define  REG_WRITE(ADDR,WDATA) (*(volatile hwint32*) (ADDR))=WDATA

#define  FIELD_READ(ADDR,MASK,OFFSET)\
((REG_READ( ADDR) & MASK) >> OFFSET)

#define  FIELD_WRITE(ADDR,WDATA,MASK,OFFSET)\
(REG_WRITE( ADDR,(((WDATA) & MASK)|(REG_READ(ADDR) & ~MASK) )))
#define READ_STATUS(ADDR)  ({int retval; retval = REG_READ(ADDR);retval;})
#define READ_STATUS_FIELD(ADDR,MASK,OFFSET)  ({int retval; retval = FIELD_READ(ADDR,MASK,OFFSET);retval;})
