//=====================================================================================================================
//All Rights Reserved.*************Agnisys**************** fadfasdfsdfsd
//*** This file is auto generated by ISequenceSpec (http://www.agnisys.com) . Please do not edit this file. ***
//Created by        :
//Generated by      : Saurabh
//Generated from    : C:\Users\Anupam\Documents\GitHub\git_test\Allegro_test\test99\sample_sequence.idsng
//IDesignSpec rev   : idsbatch v 6.16.4.7
//=====================================================================================================================


#include <stdbool.h>


int  shadow_eeprom( int pack ,int chik ) {

const int constant = 15 ;
const int real_const = 13 ;
int flag;
int variable1 = 12 ;
int variable2 = 9 ;



FIELD_WRITE(TopC_PCIe_LINK0_CORE_rx_buffer0_ADDRESS,0x0000000A,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER0_ES_RX_BUFFER0_MASK,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER0_ES_RX_BUFFER0_OFFSET);

FIELD_WRITE(TopC_PCIe_LINK0_CORE_rx_buffer0_ADDRESS,0x000C0001,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER0_ES_RX_BUFFER1_MASK,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER0_ES_RX_BUFFER1_OFFSET);

FIELD_WRITE(TopC_PCIe_LINK0_CORE_rx_buffer1_ADDRESS,0x0000000F,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER1_ES_RX_BUFFER0_MASK,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER1_ES_RX_BUFFER0_OFFSET);

FIELD_WRITE(TopC_PCIe_LINK0_CORE_rx_buffer1_ADDRESS,0x000D0000,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER1_ES_RX_BUFFER1_MASK,TOPC_PCIE_LINK0_CORE_RX_MEM_RX_BUFFER1_ES_RX_BUFFER1_OFFSET);
return flag;
}
