
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
%%%  *** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
%%% created by          : Saurabh
%%% generated by        : Saurabh
%%% generated from      : java.lang.String$CaseInsensitiveComparator@5a194dce
%%% IDesignSpec rev     :  6.16.4.7
%%% **** This code is generated with the following settings ***
%%% Reg Width                  : 32
%%% Address Unit               : 8
%%% C++ Types int              : hwint
%%% BigEndian                  : false
%%% LittleEndian               : false
%%% Dist. Decode and Readback  : false
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function Shadow_EEPROM ( pack,chik )

%%% Constant Declaration %%%
classdef Constants
properties( Constant = true )
constant = 15;
real_const = 13;
end
end

%%% Variable Declaration %%%
variable1
variable1 = 12;;
variable2
variable2 = 9;;

%%% Steps Declaration %%%
%%%% write into the field es_rx_buffer0 %%%%
FIELD_WRITE(memory_name,hextodec('1B0'),pack,15,0);
%%%% write into the field es_rx_buffer1 %%%%
FIELD_WRITE(memory_name,hextodec('1B0'),chik,31,16);
%%%% write into the field es_rx_buffer0 %%%%
FIELD_WRITE(memory_name,hextodec('1B4'),Constants.constant,15,0);
%%%% write into the field es_rx_buffer1 %%%%
FIELD_WRITE(memory_name,hextodec('1B4'),Constants.real_const,31,16);
end
