
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
%%%  *** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
%%% created by          : Saurabh
%%% generated by        : Saurabh
%%% generated from      : java.lang.String$CaseInsensitiveComparator@5a194dce
%%% IDesignSpec rev     :  6.16.4.7
%%% **** This code is generated with the following settings ***
%%% Reg Width                  : 32
%%% Address Unit               : 8
%%% C++ Types int              : hwint
%%% BigEndian                  : false
%%% LittleEndian               : false
%%% Dist. Decode and Readback  : false
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function Status_EEPROM ( arg )

%%% Constant Declaration %%%
classdef Constants
properties( Constant = true )
const1 = 3;
const2 = 4;
end
end

%%% Variable Declaration %%%
var1
var1 = 5;;

%%% Steps Declaration %%%
%%%% write into the field boot_rom_mem1 %%%%
FIELD_WRITE(memory_name,hextodec('190'),hextodec('55'),23,16);
%%%% write into the register boot_rom %%%%
REG_WRITE(memory_name,hextodec('190'),Constants.const2);
%%%% write into the field flash_mem0 %%%%
FIELD_WRITE(memory_name,hextodec('194'),var1,15,0);
%%%% write into the field flash_mem1 %%%%
FIELD_WRITE(memory_name,hextodec('194'),12,31,16);
%%%% write into the register boot_rom %%%%
REG_WRITE(memory_name,hextodec('190'),11);
Shadow_EEPROM();
%%%% write into the register boot_rom %%%%
REG_WRITE(memory_name,hextodec('190'),4);
end
