//=====================================================================================================================
//All Rights Reserved.
//*** This file is auto generated by ISequenceSpec (http://www.agnisys.com) . Please do not edit this file. ***
//Created by        :
//Generated by      : Admin
//Generated from    : C:\Users\Admin\Documents\GitHub\git_test\Allegro_test\Test2\tttt.idsng
//IDesignSpec rev   : idsbatch v4.16.26.2
//=====================================================================================================================

class uvm_seq_name_seq extends uvm_reg_sequence#(uvm_sequence#(uvm_reg_item));
    `uvm_object_utils(uvm_seq_name_seq)

    uvm_status_e status;

    block1_block rm ;

    function new(string name = "uvm_seq_name_seq") ;
        super.new(name);
        this.init();
    endfunction

    int arg1;

    function init(int arg1=11);
        this.arg1 = arg1;
    endfunction

    int var1 = 10 ;

    task body;

        if(!$cast(rm, model)) begin
            `uvm_error("RegModel : block1_block","cannot cast an object of type uvm_reg_sequence to rm");
        end

        if (rm == null)  begin
            `uvm_error("block1_block", "No register model specified to run sequence on, you should specify regmodel by using property 'uvm.regmodel' in the sequence")
            return;
        end

        for ( int i = 0 ; i < var1;i++ )
        begin

            rm.reg1.write(status, 10, .parent(this));
            if (arg1 <= 12)
                begin

                    rm.reg2.write(status, 11, .parent(this));
                end
            end

        endtask: body
    endclass: uvm_seq_name_seq
