//=====================================================================================================================
//All Rights Reserved.
//*** This file is auto generated by ISequenceSpec (http://www.agnisys.com) . Please do not edit this file. ***
//Created by        :
//Generated by      :  Admin
//Generated from    :  C:\Users\Admin\Documents\GitHub\git_test\Allegro_test\Test2\tttt.idsng
//IDesignSpec rev   :  idsbatch v4.16.26.2
//=====================================================================================================================

package chip_name_iss_pkg;
    import block1_regmem_pkg::*;
    import uvm_pkg::*;
    `include "uvm_macros.svh"

    `include "seq_name.uvm.sv"

endpackage
