/*Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. ******/
/**/
/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ****/
/* created by        : */
/* generated by      : Saurabh*/
/* generated from    : C:\Users\Anupam\Documents\GitHub\git_test\Allegro_test\debug\top.idsng*/
/* IDesignSpec rev   : idsbatch v 6.16.4.7 */

/**** This code is generated with following settings ****/
/* Reg Width                  : 32*/
/* Address Unit               : 32*/
/* C++ Types int              : hwint*/
/* Bus Type                   : PROPRIETARY*/
/* BigEndian                  : false*/
/* LittleEndian               : false*/
/* Dist. Decode and Readback  : false*/
/*--------------------------------------------------------------------------------------------------------------- */

/*block : top */

#ifndef _TOP_REGS_H_
#define _TOP_REGS_H_

typedef union {
    struct {
        hwint f : 32;           /* 0:31 SW=rw HW=ro 0x0 */
    } bf;
    hwint  dw;
    
    
} top_reg_name;

typedef struct {
    top_reg_name  reg_name;
    
    
    
} top_s;


#define top_s_SIZE 0x4
#define top_reg_name_SIZE 0x4

#define top_s_OFFSET 0x0
#define top_reg_name_OFFSET 0x0

#define top_s_ADDRESS 0x0
#define top_reg_name_ADDRESS 0x0
#define TOP_REG_NAME_F_OFFSET 0
#define TOP_REG_NAME_F_MASK 0xFFFFFFFF
#endif /* _TOP_REGS_H_ */

/* end */
