//Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created by        :
// generated by      : Admin
// generated from    : C:\Users\Admin\Documents\GitHub\git_test\Allegro_test\case1\case1.idsng
// IDesignSpec rev   : idsbatch v4.16.26.2

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 8
// C++ Types int              : hwint
// Bus Type                   : AXI
// BigEndian                  : false
// LittleEndian               : false
// Dist. Decode and Readback  : false
//---------------------------------------------------------------------------------------------------------------

//------------------------------------------------
//  BLOCK : BLOCK2 MODULE
//

module block2_ids(
    
    // REGISTER : REG1 PORT SIGNAL
    reggroup1_reg1_enb,
    reggroup1_reg1_fld_in,
    reggroup1_reg1_fld_in_enb,
    reggroup1_reg1_fld_r,
    
    
    // REGISTER : REG2 PORT SIGNAL
    reggroup1_reg2_enb,
    reggroup1_reg2_fld1_in,
    reggroup1_reg2_fld1_in_enb,
    reggroup1_reg2_fld1_r,
    
    
    // REGISTER : REG1 PORT SIGNAL
    ref_name_reg1_enb,
    ref_name_reg1_fld_in,
    ref_name_reg1_fld_in_enb,
    ref_name_reg1_fld_r,
    
    
    // REGISTER : REG1 PORT SIGNAL
    ref_name_ref_name_reggroup1_reg1_enb,
    ref_name_ref_name_reggroup1_reg1_fld_in,
    ref_name_ref_name_reggroup1_reg1_fld_in_enb,
    ref_name_ref_name_reggroup1_reg1_fld_r,
    
    
    // REGISTER : REG2 PORT SIGNAL
    ref_name_ref_name_reggroup1_reg2_enb,
    ref_name_ref_name_reggroup1_reg2_fld1_in,
    ref_name_ref_name_reggroup1_reg2_fld1_in_enb,
    ref_name_ref_name_reggroup1_reg2_fld1_r,
    
    
    
    //AXI signals
    aclk,   // Bus clock
    aresetn,   // Reset
    awaddr,   // Write address
    awvalid,   // Write address valid : This signal indicates that write address is valid
    awready,   // Write address ready : This signal indicates that the slave is ready to accept an address
    awprot,   // Write Protection Type
    wdata,   // Write data
    wvalid,   // Write valid         : This signal indicates that valid write data and strobes are available
    wready,   // Write ready         : This signal indicates that the slave can accept the write data
    wstrb,   // Write Strobes
    bresp,   // Write Response
    bready,   // Response Ready
    bvalid,   // Response valid
    araddr,   // Read  address
    arvalid,   // Read address valid  : This signal indicates that the read address is valid and will remain stable until ARREADY is high
    arready,   // Read address ready  : This signal indicates that the slave is ready to accept an address
    arprot,   // Read Protection Type
    rdata,   // Read data
    rvalid,   // Read valid          : This signal indicates that the required read data is available and the read transfer can complete
    rready,   // Read ready          : This signal indicates that the master can accept the read data
    rresp   // Read Response
    );
    //  PARAMETERS
    parameter bus_width   = 32;
    parameter addr_width = 5;
    
    parameter block_offset  = {(addr_width){1'b0}};
    
    // SECTION : REGGROUP1
    parameter reggroup1_count         = 1;
    parameter reggroup1_address_width = addr_width;
    
    // SECTION : REGGROUP1
    parameter ref_name_ref_name_reggroup1_count         = 1;
    parameter ref_name_ref_name_reggroup1_address_width = addr_width;
    
    // SECTION : REF_NAME
    parameter ref_name_count         = 1;
    parameter ref_name_address_width = addr_width;
    
    
    parameter block2_address_width = addr_width;
    //-----------------------------------------------------
    // REGISTER : REG1 SIGNALS
    
    
    wire    reggroup1_reg1_decode;         // Write DECODE
    wire    reggroup1_reg1_rdecode;        // Read  DECODE
    wire    reggroup1_reg1_wr_valid;       // WRITE VALID
    wire    reggroup1_reg1_rd_valid;       // READ VALID
    wire    [bus_width-1 : 0] reggroup1_reg1_rd_data;          // READ DATA
    wire    [64-1 : 0] reggroup1_reg1_offset;  // OFFSET
    output  reggroup1_reg1_enb;    // REGISTER ENABLE
    
    // HW WRITE-ABLE SIGNAL FOR EACH FIELD
    input   reggroup1_reg1_fld_in_enb ;      // FIELD : FLD
    
    // BUFFER SIGNAL FOR EACH FIELD
    reg [31 : 0] reggroup1_reg1_fld_q ;      // FIELD : FLD
    
    // READ DATA SIGNAL FOR EACH FIELD
    output  [31 : 0] reggroup1_reg1_fld_r ;      // FIELD : FLD
    
    // HW WRITE DATA SIGNAL FOR EACH FIELD
    input   [31 : 0] reggroup1_reg1_fld_in ;      // FIELD : FLD
    
    //-----------------------------------------------------
    
    
    //-----------------------------------------------------
    // REGISTER : REG2 SIGNALS
    
    
    wire    reggroup1_reg2_decode;         // Write DECODE
    wire    reggroup1_reg2_rdecode;        // Read  DECODE
    wire    reggroup1_reg2_wr_valid;       // WRITE VALID
    wire    reggroup1_reg2_rd_valid;       // READ VALID
    wire    [bus_width-1 : 0] reggroup1_reg2_rd_data;          // READ DATA
    wire    [64-1 : 0] reggroup1_reg2_offset;  // OFFSET
    output  reggroup1_reg2_enb;    // REGISTER ENABLE
    
    // HW WRITE-ABLE SIGNAL FOR EACH FIELD
    input   reggroup1_reg2_fld1_in_enb ;      // FIELD : FLD1
    
    // BUFFER SIGNAL FOR EACH FIELD
    reg [31 : 0] reggroup1_reg2_fld1_q ;      // FIELD : FLD1
    
    // READ DATA SIGNAL FOR EACH FIELD
    output  [31 : 0] reggroup1_reg2_fld1_r ;      // FIELD : FLD1
    
    // HW WRITE DATA SIGNAL FOR EACH FIELD
    input   [31 : 0] reggroup1_reg2_fld1_in ;      // FIELD : FLD1
    
    //-----------------------------------------------------
    
    
    //-----------------------------------------------------
    // REGISTER : REG1 SIGNALS
    
    
    wire    ref_name_reg1_decode;         // Write DECODE
    wire    ref_name_reg1_rdecode;        // Read  DECODE
    wire    ref_name_reg1_wr_valid;       // WRITE VALID
    wire    ref_name_reg1_rd_valid;       // READ VALID
    wire    [bus_width-1 : 0] ref_name_reg1_rd_data;          // READ DATA
    wire    [64-1 : 0] ref_name_reg1_offset;  // OFFSET
    output  ref_name_reg1_enb;    // REGISTER ENABLE
    
    // HW WRITE-ABLE SIGNAL FOR EACH FIELD
    input   ref_name_reg1_fld_in_enb ;      // FIELD : FLD
    
    // BUFFER SIGNAL FOR EACH FIELD
    reg [31 : 0] ref_name_reg1_fld_q ;      // FIELD : FLD
    
    // READ DATA SIGNAL FOR EACH FIELD
    output  [31 : 0] ref_name_reg1_fld_r ;      // FIELD : FLD
    
    // HW WRITE DATA SIGNAL FOR EACH FIELD
    input   [31 : 0] ref_name_reg1_fld_in ;      // FIELD : FLD
    
    //-----------------------------------------------------
    
    
    //-----------------------------------------------------
    // REGISTER : REG1 SIGNALS
    
    
    wire    ref_name_ref_name_reggroup1_reg1_decode;         // Write DECODE
    wire    ref_name_ref_name_reggroup1_reg1_rdecode;        // Read  DECODE
    wire    ref_name_ref_name_reggroup1_reg1_wr_valid;       // WRITE VALID
    wire    ref_name_ref_name_reggroup1_reg1_rd_valid;       // READ VALID
    wire    [bus_width-1 : 0] ref_name_ref_name_reggroup1_reg1_rd_data;          // READ DATA
    wire    [64-1 : 0] ref_name_ref_name_reggroup1_reg1_offset;  // OFFSET
    output  ref_name_ref_name_reggroup1_reg1_enb;    // REGISTER ENABLE
    
    // HW WRITE-ABLE SIGNAL FOR EACH FIELD
    input   ref_name_ref_name_reggroup1_reg1_fld_in_enb ;      // FIELD : FLD
    
    // BUFFER SIGNAL FOR EACH FIELD
    reg [31 : 0] ref_name_ref_name_reggroup1_reg1_fld_q ;      // FIELD : FLD
    
    // READ DATA SIGNAL FOR EACH FIELD
    output  [31 : 0] ref_name_ref_name_reggroup1_reg1_fld_r ;      // FIELD : FLD
    
    // HW WRITE DATA SIGNAL FOR EACH FIELD
    input   [31 : 0] ref_name_ref_name_reggroup1_reg1_fld_in ;      // FIELD : FLD
    
    //-----------------------------------------------------
    
    
    //-----------------------------------------------------
    // REGISTER : REG2 SIGNALS
    
    
    wire    ref_name_ref_name_reggroup1_reg2_decode;         // Write DECODE
    wire    ref_name_ref_name_reggroup1_reg2_rdecode;        // Read  DECODE
    wire    ref_name_ref_name_reggroup1_reg2_wr_valid;       // WRITE VALID
    wire    ref_name_ref_name_reggroup1_reg2_rd_valid;       // READ VALID
    wire    [bus_width-1 : 0] ref_name_ref_name_reggroup1_reg2_rd_data;          // READ DATA
    wire    [64-1 : 0] ref_name_ref_name_reggroup1_reg2_offset;  // OFFSET
    output  ref_name_ref_name_reggroup1_reg2_enb;    // REGISTER ENABLE
    
    // HW WRITE-ABLE SIGNAL FOR EACH FIELD
    input   ref_name_ref_name_reggroup1_reg2_fld1_in_enb ;      // FIELD : FLD1
    
    // BUFFER SIGNAL FOR EACH FIELD
    reg [31 : 0] ref_name_ref_name_reggroup1_reg2_fld1_q ;      // FIELD : FLD1
    
    // READ DATA SIGNAL FOR EACH FIELD
    output  [31 : 0] ref_name_ref_name_reggroup1_reg2_fld1_r ;      // FIELD : FLD1
    
    // HW WRITE DATA SIGNAL FOR EACH FIELD
    input   [31 : 0] ref_name_ref_name_reggroup1_reg2_fld1_in ;      // FIELD : FLD1
    
    //-----------------------------------------------------
    
    
    
    //AXI signals
    input aclk;
    input aresetn;
    input [addr_width-1 : 0] awaddr;
    input awvalid;
    output awready;
    input [2 : 0] awprot;
    wire  [2 : 0] awprot_i;
    input [bus_width-1 : 0] wdata;
    input wvalid;
    output wready;
    input [bus_width/8-1 : 0] wstrb;
    output [1 : 0] bresp;
    input bready;
    output bvalid;
    input [addr_width-1 : 0] araddr;
    input arvalid;
    output arready;
    input [2 : 0] arprot;
    wire  [2 : 0] arprot_i;
    output [bus_width-1 : 0] rdata;
    output rvalid;
    input rready;
    output [1 : 0] rresp;
    
    wire  clk;
    wire  reset_l;
    wire   rd_stb;
    wire   rd_wait;
    wire   wr_stb;
    wire  [addr_width-1:0]  address;
    wire  [bus_width-1:0]  wr_data;
    wire   request;
    wire  rd_data_vld;
    wire  [bus_width-1:0] rd_data;
    wire [addr_width-1 : 0] raddress;
    wire  wr_error;
    wire  rd_error;
    wire  wr_decode_error;
    wire  rd_decode_error;
    wire  wr_slave_select;
    wire  rd_slave_select;
    wire  [addr_width-1:0] slvwaddr;
    wire  [addr_width-1:0] slvraddr;
    wire [bus_width-1 : 0] reg_enb;
    wire [bus_width/8 -1 : 0] byte_enb;
    
    axi_widget #(.addr_width(addr_width), .bus_width(bus_width)) axi(
            .aclk(aclk),
            .aresetn(aresetn),
            .awaddr(awaddr),
            .awvalid(awvalid),
            .awready(awready),
            .awprot(awprot),
            .awprot_i(awprot_i),
            .wdata(wdata),
            .wvalid(wvalid),
            .wready(wready),
            .wstrb(wstrb),
            .bresp(bresp),
            .bready(bready),
            .bvalid(bvalid),
            .araddr(araddr),
            .arvalid(arvalid),
            .arready(arready),
            .arprot(arprot),
            .arprot_i(arprot_i),
            .rdata(rdata),
            .rvalid(rvalid),
            .rready(rready),
            .rresp(rresp),
            .clk(clk),
            .reset_l(reset_l),
            .request(request),
            .wr_stb(wr_stb),
            .wr_decode_error(wr_decode_error),
            .rd_decode_error(rd_decode_error),
            .wr_slave_select(wr_slave_select),
            .rd_slave_select(rd_slave_select),
            .slvwaddr(slvwaddr),
            .slvraddr(slvraddr),
            .rd_stb(rd_stb),
            .rd_wait(rd_wait),
            .wr_error(wr_error),
            .rd_error(rd_error),
            .rd_data(rd_data),
            .wr_data(wr_data),
            .address(address),
            .raddress(raddress),
            .rd_data_vld(rd_data_vld),
            .byte_enb(byte_enb));
    //end widget
    
    assign reg_enb =  {
    {8{byte_enb[3]}} ,
    {8{byte_enb[2]}} ,
    {8{byte_enb[1]}} ,
    {8{byte_enb[0]}}};
    
    
    
    
    //----------------------------------------------------------------------------------------------------
    // REGISTER      :  REG1
    // ADDRESS       :  block_offset+'h0 + 'h0                WIDTH : 32
    // HW ACCESS     :  READ-WRITE
    // SW ACCESS     :  READ-WRITE
    //
    // FIELDS   :
    //     31:0 : fld  ( SW : Read-Write HW : Read-Write )
    
    //-----------------------------------------------------------------------------
    // DESCRIPTION  :  NA
    //
    
    
    assign reggroup1_reg1_wr_valid = reggroup1_reg1_decode && wr_stb;
    assign reggroup1_reg1_rd_valid = reggroup1_reg1_rdecode && rd_stb;
    assign reggroup1_reg1_enb      = reggroup1_reg1_wr_valid;
    assign reggroup1_reg1_offset = block_offset+'h0 + 'h0;
    assign reggroup1_reg1_decode  = (address[reggroup1_address_width-1 : 0]    == reggroup1_reg1_offset[reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    assign reggroup1_reg1_rdecode = (raddress[reggroup1_address_width-1 : 0]   == reggroup1_reg1_offset[reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    
    
    //----------------------------------------------------------------------------
    // FIELD  : FLD
    // HW ACCESS  :  READ-WRITE                          WIDTH  :  32
    // SW ACCESS  :  READ-WRITE                          OFFSET :  0
    //-----------------------------------------------------------------
    // DESCRIPTION   :
    //
    
    always @(posedge clk)
        
        begin
        if (!reset_l)
            begin
                
                reggroup1_reg1_fld_q <= 32'd0;
            end
        else
            begin
            if (reggroup1_reg1_fld_in_enb)   // FLD : HW Write
                begin
                    reggroup1_reg1_fld_q <= reggroup1_reg1_fld_in;
                end
            else
                begin
                    
                if (reggroup1_reg1_wr_valid)   // FLD : SW Write
                    begin
                        reggroup1_reg1_fld_q <=  ( wr_data[31 : 0] & reg_enb[31 : 0] ) | (reggroup1_reg1_fld_q & (~reg_enb[31 : 0]));
                    end
                    
                end  // sw_write_close
            end
    end // always clk
    
    //----------------------------------------------------------------------------
    
    
    // ===================================================
    // HW OUTPUT READ DATA FOR EACH FIELD
    assign reggroup1_reg1_fld_r =  reggroup1_reg1_fld_q;    // Field : FLD
    
    
    assign reggroup1_reg1_rd_data = reggroup1_reg1_rd_valid ? {reggroup1_reg1_fld_q} : 32'b00000000000000000000000000000000;
    
    
    //----------------------------------------------------------------------------------------------------
    // REGISTER      :  REG2
    // ADDRESS       :  block_offset+'h0 + 'h4                WIDTH : 32
    // HW ACCESS     :  READ-WRITE
    // SW ACCESS     :  READ-WRITE
    //
    // FIELDS   :
    //     31:0 : fld1  ( SW : Read-Write HW : Read-Write )
    
    //-----------------------------------------------------------------------------
    // DESCRIPTION  :  NA
    //
    
    
    assign reggroup1_reg2_wr_valid = reggroup1_reg2_decode && wr_stb;
    assign reggroup1_reg2_rd_valid = reggroup1_reg2_rdecode && rd_stb;
    assign reggroup1_reg2_enb      = reggroup1_reg2_wr_valid;
    assign reggroup1_reg2_offset = block_offset+'h0 + 'h4;
    assign reggroup1_reg2_decode  = (address[reggroup1_address_width-1 : 0]    == reggroup1_reg2_offset[reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    assign reggroup1_reg2_rdecode = (raddress[reggroup1_address_width-1 : 0]   == reggroup1_reg2_offset[reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    
    
    //----------------------------------------------------------------------------
    // FIELD  : FLD1
    // HW ACCESS  :  READ-WRITE                          WIDTH  :  32
    // SW ACCESS  :  READ-WRITE                          OFFSET :  0
    //-----------------------------------------------------------------
    // DESCRIPTION   :
    //
    
    always @(posedge clk)
        
        begin
        if (!reset_l)
            begin
                
                reggroup1_reg2_fld1_q <= 32'd0;
            end
        else
            begin
            if (reggroup1_reg2_fld1_in_enb)   // FLD1 : HW Write
                begin
                    reggroup1_reg2_fld1_q <= reggroup1_reg2_fld1_in;
                end
            else
                begin
                    
                if (reggroup1_reg2_wr_valid)   // FLD1 : SW Write
                    begin
                        reggroup1_reg2_fld1_q <=  ( wr_data[31 : 0] & reg_enb[31 : 0] ) | (reggroup1_reg2_fld1_q & (~reg_enb[31 : 0]));
                    end
                    
                end  // sw_write_close
            end
    end // always clk
    
    //----------------------------------------------------------------------------
    
    
    // ===================================================
    // HW OUTPUT READ DATA FOR EACH FIELD
    assign reggroup1_reg2_fld1_r =  reggroup1_reg2_fld1_q;    // Field : FLD1
    
    
    assign reggroup1_reg2_rd_data = reggroup1_reg2_rd_valid ? {reggroup1_reg2_fld1_q} : 32'b00000000000000000000000000000000;
    
    
    
    //----------------------------------------------------------------------------------------------------
    // REGISTER      :  REG1
    // ADDRESS       :  block_offset+'h8 + 'h0                WIDTH : 32
    // HW ACCESS     :  READ-WRITE
    // SW ACCESS     :  READ-WRITE
    //
    // FIELDS   :
    //     31:0 : fld  ( SW : Read-Write HW : Read-Write )
    
    //-----------------------------------------------------------------------------
    // DESCRIPTION  :  NA
    //
    
    
    assign ref_name_reg1_wr_valid = ref_name_reg1_decode && wr_stb;
    assign ref_name_reg1_rd_valid = ref_name_reg1_rdecode && rd_stb;
    assign ref_name_reg1_enb      = ref_name_reg1_wr_valid;
    assign ref_name_reg1_offset = block_offset+'h8 + 'h0;
    assign ref_name_reg1_decode  = (address[ref_name_address_width-1 : 0]    == ref_name_reg1_offset[ref_name_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    assign ref_name_reg1_rdecode = (raddress[ref_name_address_width-1 : 0]   == ref_name_reg1_offset[ref_name_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    
    
    //----------------------------------------------------------------------------
    // FIELD  : FLD
    // HW ACCESS  :  READ-WRITE                          WIDTH  :  32
    // SW ACCESS  :  READ-WRITE                          OFFSET :  0
    //-----------------------------------------------------------------
    // DESCRIPTION   :
    //
    
    always @(posedge clk)
        
        begin
        if (!reset_l)
            begin
                
                ref_name_reg1_fld_q <= 32'd0;
            end
        else
            begin
            if (ref_name_reg1_fld_in_enb)   // FLD : HW Write
                begin
                    ref_name_reg1_fld_q <= ref_name_reg1_fld_in;
                end
            else
                begin
                    
                if (ref_name_reg1_wr_valid)   // FLD : SW Write
                    begin
                        ref_name_reg1_fld_q <=  ( wr_data[31 : 0] & reg_enb[31 : 0] ) | (ref_name_reg1_fld_q & (~reg_enb[31 : 0]));
                    end
                    
                end  // sw_write_close
            end
    end // always clk
    
    //----------------------------------------------------------------------------
    
    
    // ===================================================
    // HW OUTPUT READ DATA FOR EACH FIELD
    assign ref_name_reg1_fld_r =  ref_name_reg1_fld_q;    // Field : FLD
    
    
    assign ref_name_reg1_rd_data = ref_name_reg1_rd_valid ? {ref_name_reg1_fld_q} : 32'b00000000000000000000000000000000;
    
    
    //----------------------------------------------------------------------------------------------------
    // REGISTER      :  REG1
    // ADDRESS       :  block_offset+'h8 + 'h4 + 'h0                WIDTH : 32
    // HW ACCESS     :  READ-WRITE
    // SW ACCESS     :  READ-WRITE
    //
    // FIELDS   :
    //     31:0 : fld  ( SW : Read-Write HW : Read-Write )
    
    //-----------------------------------------------------------------------------
    // DESCRIPTION  :  NA
    //
    
    
    assign ref_name_ref_name_reggroup1_reg1_wr_valid = ref_name_ref_name_reggroup1_reg1_decode && wr_stb;
    assign ref_name_ref_name_reggroup1_reg1_rd_valid = ref_name_ref_name_reggroup1_reg1_rdecode && rd_stb;
    assign ref_name_ref_name_reggroup1_reg1_enb      = ref_name_ref_name_reggroup1_reg1_wr_valid;
    assign ref_name_ref_name_reggroup1_reg1_offset = block_offset+'h8 + 'h4 + 'h0;
    assign ref_name_ref_name_reggroup1_reg1_decode  = (address[ref_name_ref_name_reggroup1_address_width-1 : 0]    == ref_name_ref_name_reggroup1_reg1_offset[ref_name_ref_name_reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    assign ref_name_ref_name_reggroup1_reg1_rdecode = (raddress[ref_name_ref_name_reggroup1_address_width-1 : 0]   == ref_name_ref_name_reggroup1_reg1_offset[ref_name_ref_name_reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    
    
    //----------------------------------------------------------------------------
    // FIELD  : FLD
    // HW ACCESS  :  READ-WRITE                          WIDTH  :  32
    // SW ACCESS  :  READ-WRITE                          OFFSET :  0
    //-----------------------------------------------------------------
    // DESCRIPTION   :
    //
    
    always @(posedge clk)
        
        begin
        if (!reset_l)
            begin
                
                ref_name_ref_name_reggroup1_reg1_fld_q <= 32'd0;
            end
        else
            begin
            if (ref_name_ref_name_reggroup1_reg1_fld_in_enb)   // FLD : HW Write
                begin
                    ref_name_ref_name_reggroup1_reg1_fld_q <= ref_name_ref_name_reggroup1_reg1_fld_in;
                end
            else
                begin
                    
                if (ref_name_ref_name_reggroup1_reg1_wr_valid)   // FLD : SW Write
                    begin
                        ref_name_ref_name_reggroup1_reg1_fld_q <=  ( wr_data[31 : 0] & reg_enb[31 : 0] ) | (ref_name_ref_name_reggroup1_reg1_fld_q & (~reg_enb[31 : 0]));
                    end
                    
                end  // sw_write_close
            end
    end // always clk
    
    //----------------------------------------------------------------------------
    
    
    // ===================================================
    // HW OUTPUT READ DATA FOR EACH FIELD
    assign ref_name_ref_name_reggroup1_reg1_fld_r =  ref_name_ref_name_reggroup1_reg1_fld_q;    // Field : FLD
    
    
    assign ref_name_ref_name_reggroup1_reg1_rd_data = ref_name_ref_name_reggroup1_reg1_rd_valid ? {ref_name_ref_name_reggroup1_reg1_fld_q} : 32'b00000000000000000000000000000000;
    
    
    //----------------------------------------------------------------------------------------------------
    // REGISTER      :  REG2
    // ADDRESS       :  block_offset+'h8 + 'h4 + 'h4                WIDTH : 32
    // HW ACCESS     :  READ-WRITE
    // SW ACCESS     :  READ-WRITE
    //
    // FIELDS   :
    //     31:0 : fld1  ( SW : Read-Write HW : Read-Write )
    
    //-----------------------------------------------------------------------------
    // DESCRIPTION  :  NA
    //
    
    
    assign ref_name_ref_name_reggroup1_reg2_wr_valid = ref_name_ref_name_reggroup1_reg2_decode && wr_stb;
    assign ref_name_ref_name_reggroup1_reg2_rd_valid = ref_name_ref_name_reggroup1_reg2_rdecode && rd_stb;
    assign ref_name_ref_name_reggroup1_reg2_enb      = ref_name_ref_name_reggroup1_reg2_wr_valid;
    assign ref_name_ref_name_reggroup1_reg2_offset = block_offset+'h8 + 'h4 + 'h4;
    assign ref_name_ref_name_reggroup1_reg2_decode  = (address[ref_name_ref_name_reggroup1_address_width-1 : 0]    == ref_name_ref_name_reggroup1_reg2_offset[ref_name_ref_name_reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    assign ref_name_ref_name_reggroup1_reg2_rdecode = (raddress[ref_name_ref_name_reggroup1_address_width-1 : 0]   == ref_name_ref_name_reggroup1_reg2_offset[ref_name_ref_name_reggroup1_address_width-1 : 0] ) ? 1'b1 : 1'b0;
    
    
    //----------------------------------------------------------------------------
    // FIELD  : FLD1
    // HW ACCESS  :  READ-WRITE                          WIDTH  :  32
    // SW ACCESS  :  READ-WRITE                          OFFSET :  0
    //-----------------------------------------------------------------
    // DESCRIPTION   :
    //
    
    always @(posedge clk)
        
        begin
        if (!reset_l)
            begin
                
                ref_name_ref_name_reggroup1_reg2_fld1_q <= 32'd0;
            end
        else
            begin
            if (ref_name_ref_name_reggroup1_reg2_fld1_in_enb)   // FLD1 : HW Write
                begin
                    ref_name_ref_name_reggroup1_reg2_fld1_q <= ref_name_ref_name_reggroup1_reg2_fld1_in;
                end
            else
                begin
                    
                if (ref_name_ref_name_reggroup1_reg2_wr_valid)   // FLD1 : SW Write
                    begin
                        ref_name_ref_name_reggroup1_reg2_fld1_q <=  ( wr_data[31 : 0] & reg_enb[31 : 0] ) | (ref_name_ref_name_reggroup1_reg2_fld1_q & (~reg_enb[31 : 0]));
                    end
                    
                end  // sw_write_close
            end
    end // always clk
    
    //----------------------------------------------------------------------------
    
    
    // ===================================================
    // HW OUTPUT READ DATA FOR EACH FIELD
    assign ref_name_ref_name_reggroup1_reg2_fld1_r =  ref_name_ref_name_reggroup1_reg2_fld1_q;    // Field : FLD1
    
    
    assign ref_name_ref_name_reggroup1_reg2_rd_data = ref_name_ref_name_reggroup1_reg2_rd_valid ? {ref_name_ref_name_reggroup1_reg2_fld1_q} : 32'b00000000000000000000000000000000;
    
    
    
    
    
    
    
    
    
    
    
    
    assign rd_data = reggroup1_reg1_rd_data |
    reggroup1_reg2_rd_data |
    ref_name_reg1_rd_data |
    ref_name_ref_name_reggroup1_reg1_rd_data |
    ref_name_ref_name_reggroup1_reg2_rd_data ;
    
    
    
    assign wr_error = 0;
    
    assign rd_error = 0;
    
    assign wr_decode_error = 0;
    
    assign rd_decode_error = 0;
    
    assign request      =  1'b1;
    assign rd_data_vld   =  rd_stb;
    assign rd_wait       =  1'b1;
    
    assign wr_slave_select = ((slvwaddr[addr_width - 1 : 0]  >= block_offset) && (slvwaddr[addr_width - 1 : 0]  <= block_offset + 'h13)) ? 1'b1 : 1'b0;
    assign rd_slave_select = ((slvraddr[addr_width - 1 : 0]  >= block_offset) && (slvraddr[addr_width - 1 : 0]  <= block_offset + 'h13)) ? 1'b1 : 1'b0;
    
endmodule
