//Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created by        :
// generated by      : Admin
// generated from    : C:\Users\Admin\Documents\GitHub\git_test\Allegro_test\case1\case1.idsng
// IDesignSpec rev   : idsbatch v4.16.26.2

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 8
// C++ Types int              : hwint
// Bus Type                   : AXI
// BigEndian                  : false
// LittleEndian               : false
// Dist. Decode and Readback  : false
//---------------------------------------------------------------------------------------------------------------
`include "case1.formal.sv"


module chip_name_onespin;
    
    bind chip_name_ids chip_name_ids_assert chip_name_assert (.block1_idsreg1_fld_q(block1_idsinst._fld_q),
    .block1_idsreg1_wr_valid(block1_idsinst.reg1_wr_valid),
    .block1_idsreg1_rd_valid(block1_idsinst.reg1_rd_valid),
    .block1_idsreggroup1_reg1_fld_q(block1_idsinst._fld_q),
    .block1_idsreggroup1_reg1_wr_valid(block1_idsinst.reggroup1_reg1_wr_valid),
    .block1_idsreggroup1_reg1_rd_valid(block1_idsinst.reggroup1_reg1_rd_valid),
    .block1_idsreggroup1_reg2_fld1_q(block1_idsinst._fld1_q),
    .block1_idsreggroup1_reg2_wr_valid(block1_idsinst.reggroup1_reg2_wr_valid),
    .block1_idsreggroup1_reg2_rd_valid(block1_idsinst.reggroup1_reg2_rd_valid),
    .block2_idsreggroup1_reg1_fld_q(block2_idsinst._fld_q),
    .block2_idsreggroup1_reg1_wr_valid(block2_idsinst.reggroup1_reg1_wr_valid),
    .block2_idsreggroup1_reg1_rd_valid(block2_idsinst.reggroup1_reg1_rd_valid),
    .block2_idsreggroup1_reg2_fld1_q(block2_idsinst._fld1_q),
    .block2_idsreggroup1_reg2_wr_valid(block2_idsinst.reggroup1_reg2_wr_valid),
    .block2_idsreggroup1_reg2_rd_valid(block2_idsinst.reggroup1_reg2_rd_valid),
    .block2_idsref_name_reg1_fld_q(block2_idsinst._fld_q),
    .block2_idsref_name_reg1_wr_valid(block2_idsinst.ref_name_reg1_wr_valid),
    .block2_idsref_name_reg1_rd_valid(block2_idsinst.ref_name_reg1_rd_valid),
    .block2_idsref_name_ref_name_reggroup1_reg1_fld_q(block2_idsinst._fld_q),
    .block2_idsref_name_ref_name_reggroup1_reg1_wr_valid(block2_idsinst.ref_name_ref_name_reggroup1_reg1_wr_valid),
    .block2_idsref_name_ref_name_reggroup1_reg1_rd_valid(block2_idsinst.ref_name_ref_name_reggroup1_reg1_rd_valid),
    .block2_idsref_name_ref_name_reggroup1_reg2_fld1_q(block2_idsinst._fld1_q),
    .block2_idsref_name_ref_name_reggroup1_reg2_wr_valid(block2_idsinst.ref_name_ref_name_reggroup1_reg2_wr_valid),
    .block2_idsref_name_ref_name_reggroup1_reg2_rd_valid(block2_idsinst.ref_name_ref_name_reggroup1_reg2_rd_valid),
    .*);
    
endmodule
