//***** Agnisys, Inc.***** Copyright 2018 All Rights Reserved. ***** *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created by        : Agni27
// generated by      : Admin
// generated from    : C:\Users\Admin\Documents\GitHub\git_test\Allegro_test\case1\case1.idsng
// IDesignSpec rev   : 4.16.26.2
//--------------------------------------------------------------------------------------------------------------- 
parameter CHIP_NAME_ADDR = 'h00 ;
parameter CHIP_NAME_SIZE = 'h20 ;

parameter CHIP_NAME_BLOCK1_ADDR = 'h00 ;
parameter CHIP_NAME_BLOCK1_SIZE = 'hc ;

parameter BLOCK1_REG1_ADDR = 'h00 ;
parameter BLOCK1_REG1_DEFAULT = 'h00000000 ;

parameter BLOCK1_REG1_FLD_MSB = 31 ;
parameter BLOCK1_REG1_FLD_LSB = 0 ;
parameter BLOCK1_REG1_FLD_DEFAULT = 'h00000000 ;

parameter BLOCK1_REGGROUP1_ADDR = 'h4 ;
parameter BLOCK1_REGGROUP1_SIZE =  'h8 ;
parameter BLOCK1_REGGROUP1_REPEAT = 1 ;

parameter BLOCK1_REGGROUP1_REG1_ADDR = 'h04 ;
parameter BLOCK1_REGGROUP1_REG1_DEFAULT = 'h00000000 ;

parameter BLOCK1_REGGROUP1_REG1_FLD_MSB = 31 ;
parameter BLOCK1_REGGROUP1_REG1_FLD_LSB = 0 ;
parameter BLOCK1_REGGROUP1_REG1_FLD_DEFAULT = 'h00000000 ;

parameter BLOCK1_REGGROUP1_REG2_ADDR = 'h08 ;
parameter BLOCK1_REGGROUP1_REG2_DEFAULT = 'h00000000 ;

parameter BLOCK1_REGGROUP1_REG2_FLD1_MSB = 31 ;
parameter BLOCK1_REGGROUP1_REG2_FLD1_LSB = 0 ;
parameter BLOCK1_REGGROUP1_REG2_FLD1_DEFAULT = 'h00000000 ;

parameter CHIP_NAME_BLOCK2_ADDR = 'h0C ;
parameter CHIP_NAME_BLOCK2_SIZE = 'h14 ;

parameter BLOCK2_REGGROUP1_ADDR = 'hc ;
parameter BLOCK2_REGGROUP1_SIZE =  'h8 ;
parameter BLOCK2_REGGROUP1_REPEAT = 1 ;

parameter BLOCK2_REGGROUP1_REG1_ADDR = 'h0C ;
parameter BLOCK2_REGGROUP1_REG1_DEFAULT = 'h00000000 ;

parameter BLOCK2_REGGROUP1_REG1_FLD_MSB = 31 ;
parameter BLOCK2_REGGROUP1_REG1_FLD_LSB = 0 ;
parameter BLOCK2_REGGROUP1_REG1_FLD_DEFAULT = 'h00000000 ;

parameter BLOCK2_REGGROUP1_REG2_ADDR = 'h10 ;
parameter BLOCK2_REGGROUP1_REG2_DEFAULT = 'h00000000 ;

parameter BLOCK2_REGGROUP1_REG2_FLD1_MSB = 31 ;
parameter BLOCK2_REGGROUP1_REG2_FLD1_LSB = 0 ;
parameter BLOCK2_REGGROUP1_REG2_FLD1_DEFAULT = 'h00000000 ;

parameter BLOCK2_REF_NAME_ADDR = 'h14 ;
parameter BLOCK2_REF_NAME_SIZE =  'hC ;
parameter BLOCK2_REF_NAME_REPEAT = 1 ;

parameter REF_NAME_REG1_ADDR = 'h14 ;
parameter REF_NAME_REG1_DEFAULT = 'h00000000 ;

parameter REF_NAME_REG1_FLD_MSB = 31 ;
parameter REF_NAME_REG1_FLD_LSB = 0 ;
parameter REF_NAME_REG1_FLD_DEFAULT = 'h00000000 ;

parameter BLOCK2_REF_NAME_REGGROUP1_ADDR = 'h18 ;
parameter BLOCK2_REF_NAME_REGGROUP1_SIZE =  'h8 ;
parameter BLOCK2_REF_NAME_REGGROUP1_REPEAT = 1 ;

parameter REF_NAME_REGGROUP1_REG1_ADDR = 'h18 ;
parameter REF_NAME_REGGROUP1_REG1_DEFAULT = 'h00000000 ;

parameter REF_NAME_REGGROUP1_REG1_FLD_MSB = 31 ;
parameter REF_NAME_REGGROUP1_REG1_FLD_LSB = 0 ;
parameter REF_NAME_REGGROUP1_REG1_FLD_DEFAULT = 'h00000000 ;

parameter REF_NAME_REGGROUP1_REG2_ADDR = 'h1C ;
parameter REF_NAME_REGGROUP1_REG2_DEFAULT = 'h00000000 ;

parameter REF_NAME_REGGROUP1_REG2_FLD1_MSB = 31 ;
parameter REF_NAME_REGGROUP1_REG2_FLD1_LSB = 0 ;
parameter REF_NAME_REGGROUP1_REG2_FLD1_DEFAULT = 'h00000000 ;

