/*Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. ******/
/**/
/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ****/
/* created by        : */
/* generated by      : Admin*/
/* generated from    : C:\Users\Admin\Documents\GitHub\git_test\Allegro_test\case1\case1.idsng*/
/* IDesignSpec rev   : idsbatch v4.16.26.2*/

/**** This code is generated with following settings ****/
/* Reg Width                  : 32*/
/* Address Unit               : 8*/
/* C++ Types int              : hwint*/
/* Bus Type                   : PROPRIETARY*/
/* BigEndian                  : false*/
/* LittleEndian               : false*/
/* Dist. Decode and Readback  : false*/
/*--------------------------------------------------------------------------------------------------------------- */

/*block : case1 */

#ifndef _CASE1_REGS_H_
#define _CASE1_REGS_H_

/*  REG1 DESCRIPTION : */
typedef union {
    struct {
        hwint fld : 32;           /* 0:31 SW=rw HW=ro  */
    } bf;
    hwint  dw;
    
    
} case1_reg1;

typedef struct {
    case1_reg1  reg1;
    
    
    
} case1_s;


#define case1_s_SIZE 0x4
#define case1_reg1_SIZE 0x4

#define case1_s_OFFSET 0x0
#define case1_reg1_OFFSET 0x0

#define case1_s_ADDRESS 0x0
#define case1_reg1_ADDRESS 0x0
#define CASE1_REG1_FLD_OFFSET 0
#define CASE1_REG1_FLD_MASK 0xFFFFFFFF
#endif /* _CASE1_REGS_H_ */

/* end */
