//Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created on        : 2019-12-02T18:19:54.441+05:30
// created by        :
// generated by      : Saurabh
// generated from    : F:\testGit\git_test\Sample467\test514\fas.idsng
// IDesignSpec rev   : idsbatch v 6.16.4.7

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 8
// C++ Types int              : hwint
// Bus Type                   : PROPRIETARY
// BigEndian                  : false
// LittleEndian               : false
// Dist. Decode and Readback  : false
//---------------------------------------------------------------------------------------------------------------

`ifndef FAS_REGMEM
`define FAS_REGMEM

package fas_regmem_pkg;
    import uvm_pkg::*;
    `include "uvm_macros.svh"

    `include "fas.regmem.sv"

endpackage
`endif
