/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
** created by        :
** generated by      : Agnisys
** generated from    : D:\AgnisysProjects\git_test\Allegro_test\Test\test26.idsng
** IDesignSpec rev   : idsbatch v4.16.26.2

***** This code is generated with following settings ***
**---------------------------------------------------------------------------------------------------------------*/



#include "Access.h"
#include "bklsRegisters.h"

namespace DUOLOG
{
    
    
    /*****************************************************************************/
    
    /**
    *regname class constructor.
    * This creates an instance of the Register object that is used to represent
    * the regnameregister. In addition, an instance of the Bitfield object is
    * created for each bitfield associated with the regname register and is then
    * associated with the register object.
    */
    regname::regname()
    {
        // Create a new instance of the Bitfield object to represent f  bitfield
        m_bff = new Bitfield<U8T> (2, 6, WRITE, READ);
        // Create a new instance of the Bitfield object to represent f2  bitfield
        m_bff2 = new Bitfield<U8T> (1, 1, WRITE, READ);
        // Declare an array containing pointers to all bitfields associated with the
        // regname register
        Bitfield<U8T> * bitfields [] = {
        m_bff,
        m_bff2
    };
    // Create a new instance of the Register object to represent regname register
    m_register = new Register<U8T> (8, 0x00, 2, bitfields);
}

/**
* Returns pointer to regname Register object.
* @return Pointer to regname Register object (Register *).
*/
Register<U8T> * regname::getRegister()
{
    return m_register;
}


/**
* Returns a pointer to the f Bitfield Object
* @return Pointer to the f Bitfield Object (Bitfield *).
*/
Bitfield<U8T> * regname::getf()
{
    return m_bff;
}


/**
* Returns a pointer to the f2 Bitfield Object
* @return Pointer to the f2 Bitfield Object (Bitfield *).
*/
Bitfield<U8T> * regname::getf2()
{
    return m_bff2;
}

} // namespace DUOLOG
