/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
** created by        :
** generated by      : Agnisys
** generated from    : D:\AgnisysProjects\git_test\Allegro_test\Test\test26.idsng
** IDesignSpec rev   : idsbatch v4.16.26.2

***** This code is generated with following settings ***
**---------------------------------------------------------------------------------------------------------------*/


#ifndef __BKLS_H
#define __BKLS_H

#include "Access.h"
#include "bklsRegisters.h"
#include "LocatedRegister.h"

namespace DUOLOG
{
    
    class bkls
    {
        private:
        // ------------------------------------------------------------------------
        // Private member variables
        // ------------------------------------------------------------------------
        regname * m_regregname;
        // Pointer to LocatedRegister object representing regname at address 0x000
        LocatedRegister<U8T> * m_locbkls_intfregname;
        // ------------------------------------------------------------------------
        // Private member variables
        // ------------------------------------------------------------------------
        // Creates register objects
        void createRegisters();
        // Creates memory objects
        void createMemories();
        // Locates registers
        void locateRegisters();
        // Locates memories
        void locateMemories();
        
        public:
        // ------------------------------------------------------------------------
        // Public member variables
        // ------------------------------------------------------------------------
        // regname register offset address definition(s)
        static const U8T BKLS_INTF_REGNAME_ADDRESS = 0x000;
        
        
        
        
        // bkls transaction port enumerations
        enum transactionPortType {
        bkls_INTF_TRANSACTION_PORT
    };
    // ------------------------------------------------------------------------
    // Public member functions
    // ------------------------------------------------------------------------
    // Class constructor
    bkls();
    // Initialises all registers in the component
    void initialise();
    // Returns a pointer to the regname object representing regname
    regname * getregname();
    // Returns pointer to LocatedRegister object representing regname at address 0x000
    LocatedRegister<U8T> * getbkls_intfregname();
    // Write access function for regname at address 0x000
    void  writebkls_intfregname(U8T  data, U8T dataMask);
    // Write access function for bkls component bkls_intf transaction target
    void  writebkls_intf(  address,  data,  dataMask);
    // Write byte lanes access function for bkls component bkls_intf transaction target
    void  writeByteLanesbkls_intf(  address, U8T BE,  data);
    // Write access function for component
    void  write (transactionPortType transactionPort,   address,  data,  dataMask);
    // Read access function for regname at address 0x000
    U8T readbkls_intfregname();
    // Read access function for bkls component bkls_intf transaction target
    readbkls_intf(  address);
    // Read byte lanes access function for bkls component bkls_intf transaction target
    readByteLanesbkls_intf(  address, U8T BE);
    // Read access function for component
    read(transactionPortType transactionPort,   address);
};

} // namespace DUOLOG
#endif /* __CTT_H */
