/*Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. ******/
/**/
/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ****/
/* created by        : */
/* generated by      : Agnisys*/
/* generated from    : D:\AgnisysProjects\git_test\Allegro_test\Test\Book1.idsng*/
/* IDesignSpec rev   : idsbatch v4.16.26.2*/

/**** This code is generated with following settings ****/
/* Reg Width                  : 32*/
/* Address Unit               : 8*/
/* C++ Types int              : hwint*/
/* Bus Type                   : PROPRIETARY*/
/* BigEndian                  : false*/
/* LittleEndian               : false*/
/* Dist. Decode and Readback  : false*/
/*--------------------------------------------------------------------------------------------------------------- */

/*//////////////////  Chip : chip1 ///////////////////*/

#ifndef _CHIP1_REGS_H_
#define _CHIP1_REGS_H_

/*block : block421 */
/*  BLOCK421 DESCRIPTION :,*/


/*section : reggroup1 */
/*  REGGROUP1 DESCRIPTION :,*/

typedef union {
    struct {
        hwint reggroup1 : 32;           /* 0:31 SW=ro HW=rw 0x0 */
    } bf;
    hwint  dw;
} chip1_block421_reggroup1;

typedef struct {
    
    union {
        chip1_block421_reggroup1 s;
        hwint8 filler[0x4];
    } reggroup1[0xA];
    
    
    
} chip1_block421_s;


/*block : block1 */


/*section : reggroup1 */

typedef union {
    struct {
        hwint f2 : 16;           /* 31:16 SW=rw HW=rw 0x0 */
        hwint f1 : 16;           /* 15:0 SW=rw HW=rw 0x0 */
    } bf;
    hwint  dw;
} chip1_block1_reg2;

typedef struct {
    chip1_block1_reg2  reg2;
    
    
    
} chip1_block1_reggroup1;


typedef struct {
    
    union {
        chip1_block1_reggroup1 s;
        hwint8 filler[0x4];
    } reggroup1;
    
    
    
} chip1_block1_s;


/*block : block3 */


/*section : reggroup1 */

typedef union {
    struct {
        hwint f2 : 16;           /* 31:16 SW=ro HW=rw 0x0 */
        hwint f1 : 16;           /* 15:0 SW=ro HW=rw 0x0 */
    } bf;
    hwint  dw;
} chip1_block3_reg2;

typedef struct {
    chip1_block3_reg2  reg2;
    
    
    
} chip1_block3_reggroup1;


typedef struct {
    
    union {
        chip1_block3_reggroup1 s;
        hwint8 filler[0x4];
    } reggroup1;
    
    
    
} chip1_block3_s;


/* chip : chip1 */







typedef struct {
    
    union {
        chip1_block421_s s;
        hwint8 filler[0x28];
    } block421[0xA];
    
    
    union {
        chip1_block1_s s;
        hwint8 filler[0x4];
    } block1;
    
    
    union {
        chip1_block3_s s;
        hwint8 filler[0x4];
    } block3;
    
    
} chip1_s;


#define chip1_s_SIZE 0x198
#define chip1_block421_s_SIZE 0x190
#define chip1_block421_reggroup1_SIZE 0x28
#define chip1_block1_s_SIZE 0x4
#define chip1_block1_reggroup1_SIZE 0x4
#define chip1_block1_reg2_SIZE 0x4
#define chip1_block3_s_SIZE 0x4
#define chip1_block3_reggroup1_SIZE 0x4
#define chip1_block3_reg2_SIZE 0x4

#define chip1_s_OFFSET 0x0
#define chip1_block421_s_OFFSET 0x0
#define chip1_block421_reggroup1_OFFSET 0x0
#define chip1_block1_s_OFFSET 0x190
#define chip1_block1_reggroup1_OFFSET 0x0
#define chip1_block1_reg2_OFFSET 0x0
#define chip1_block3_s_OFFSET 0x194
#define chip1_block3_reggroup1_OFFSET 0x0
#define chip1_block3_reg2_OFFSET 0x0

#define chip1_s_ADDRESS 0x000
#define chip1_block421_s_ADDRESS 0x000
#define chip1_block421_reggroup1_ADDRESS 0x000
#define chip1_block1_s_ADDRESS 0x190
#define chip1_block1_reggroup1_ADDRESS 0x190
#define chip1_block1_reg2_ADDRESS 0x190
#define chip1_block3_s_ADDRESS 0x194
#define chip1_block3_reggroup1_ADDRESS 0x194
#define chip1_block3_reg2_ADDRESS 0x194

#define CHIP1_BLOCK421_REGGROUP1_MEM_OFFSET 0
#define CHIP1_BLOCK421_REGGROUP1_MEM_MASK 0xFFFFFFFF
#define CHIP1_BLOCK1_REGGROUP1_REG2_F2_OFFSET 16  /* F2 DESCRIPTION :  */
#define CHIP1_BLOCK1_REGGROUP1_REG2_F2_MASK 0xFFFF0000
#define CHIP1_BLOCK1_REGGROUP1_REG2_F1_OFFSET 0  /* F1 DESCRIPTION :  */
#define CHIP1_BLOCK1_REGGROUP1_REG2_F1_MASK 0xFFFF
#define CHIP1_BLOCK3_REGGROUP1_REG2_F2_OFFSET 16  /* F2 DESCRIPTION :  */
#define CHIP1_BLOCK3_REGGROUP1_REG2_F2_MASK 0xFFFF0000
#define CHIP1_BLOCK3_REGGROUP1_REG2_F1_OFFSET 0  /* F1 DESCRIPTION :  */
#define CHIP1_BLOCK3_REGGROUP1_REG2_F1_MASK 0xFFFF
#endif /* _CHIP1_REGS_H_ */

/* end */
