/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
** created by        :
** generated by      : Agnisys
** generated from    : D:\AgnisysProjects\git_test\Allegro_test\Test\test31.idsng
** IDesignSpec rev   : idsbatch v4.16.26.2

***** This code is generated with following settings ***
**---------------------------------------------------------------------------------------------------------------*/



#include "Access.h"
#include "test31.h"

namespace DUOLOG
{
    
    /**
    * test31 class constructor.
    * This creates instances of all objects required to represent the registers
    * and memories within the test31 component.
    */
    test31::test31()
    {
        // Create register objects
        createRegisters();
        // Create memory objects
        createMemories();
        // Locate registers
        locateRegisters();
        // Locate memories
        locateMemories();
    }
    /**
    * Creates register objects
    */
    void test31::createRegisters()
    {
        // Create a new instance of the regname class to represent regname register
        m_regregname = new regname;
        return;
    }
    
    /**
    * Creates memory objects
    */
    void test31::createMemories()
    {
        return;
    }
    /**
    * Locates register objects
    */
    void test31::locateRegisters()
    {
        // Create a new instance of the LocatedRegister object to represent regname register
        // at address 0x000
        m_loctest31_intfregname = new LocatedRegister<U32T> (
        m_regregname->getRegister(),
        TEST31_INTF_REGNAME_ADDRESS,
        WRITE, READ);
        return;
    }
    
    /**
    * Locates memory objects
    */
    void test31::locateMemories()
    {
        return;
    }
    /**
    * Initialises all registers within component to power-on-reset state.
    */
    void test31::initialise()
    {
        m_regregname->getRegister()->initialise();
        return;
    }
    
    /**
    * Returns a pointer to the regname object representing regname
    * @return Pointer to the  regname object representing regname (regname *).
    */
    regname * test31::getregname()
    {
        return  m_regregname;
    }
    
    /**
    * Returns pointer to LocatedRegister object representing regname at address 0x000
    * @return Pointer to LocatedRegister object representing regname at address 0x000
    *         (LocatedRegister *).
    */
    LocatedRegister<U32T> * test31::gettest31_intfregname()
    {
        return  m_loctest31_intfregname;
    }
    
    /**
    * Write access function for regname at address 0x000
    * @param Register data value (U32T).
    * @param Register data mask (U32T).
    */
    void test31::writetest31_intfregname(U32T data, U32T dataMask)
    {
        m_loctest31_intfregname->write(data, dataMask);
    }
    
    /**
    * Write access function for test31 component test31_intf transaction target.
    * @param Register address value (U32T).
    * @param Register data value (U32T).
    * @param Register data mask (U32T).
    */
    void test31::writetest31_intf(U32T address, U32T data, U32T dataMask)
    {
        
        switch (address)
        {
            // test31_intfregname
            case TEST31_INTF_REGNAME_ADDRESS:
            writetest31_intfregname((U32T)data, (U32T)dataMask);
            break;
            // Default
            default:
            break;
        }
        return;
    }
    
    /**
    * Write byte lanes access function for test31 component test31_intf transaction target.
    * @param Register address value (U32T).
    * @param Byte lane enable (U8T).
    * @param Register data value (U32T).
    */
    void test31::writeByteLanestest31_intf(U32T address, U8T BE, U32T data)
    {
        // Determine data mask
        U32T dataMask = 0;
        for (int i = 0; i < 4; i++)
        {
            if (((BE >> i) % 2) == 1)
            {
                dataMask |= (U32T)0xff << (i * 8);
            }
        }
        
        // test31_intfregname (in byte lanes 0 to 3)
        if ((address == (TEST31_INTF_REGNAME_ADDRESS & 0xfffffffc)) &&
        (((BE % 2) == 1) ||
        (((BE >> 1) % 2) == 1) ||
        (((BE >> 2) % 2) == 1) ||
        (((BE >> 3) % 2) == 1)))
        {
            writetest31_intfregname((U32T)data, (U32T)dataMask);
        }
        
        return;
    }
    
    /**
    * Write access function for test31 component.
    * @param Register address value (U32T).
    * @param Transaction port (transactionPortType).
    * @param Register data value (U32T).
    * @param Register data mask (U32T).
    */
    void test31::write(transactionPortType transactionPort, U32T address, U32T data, U32T dataMask)
    {
        switch (transactionPort)
        {
            // test31_intf
            case test31_INTF_TRANSACTION_PORT:
            writetest31_intf(address, (U32T)data, (U32T)dataMask);
            break;
            // Default
            default:
            break;
        }
        return;
    }
    
    /**
    * Read access function for regname at address 0x000
    * @return Register data value (U32T).
    */
    U32T test31::readtest31_intfregname()
    {
        return  m_loctest31_intfregname->read();
    }
    
    /**
    * Read access function for test31_intf component test31_intf transaction target.
    * @param Register address value (U32T).
    * @retrun Register data value (U32T).
    */
    U32T test31::readtest31_intf(U32T address )
    {
        // Initialise return value
        U32T retVal = 0;
        switch (address)
        {
            // test31_intfregname
            case TEST31_INTF_REGNAME_ADDRESS:
            retVal = readtest31_intfregname();
            break;
            // Default
            default:
            break;
        }
        return retVal;
    }
    
    /**
    * Read byte lanes access function for test31 component test31_intf transaction target.
    * @param Register address value (U32T).
    * @param Byte lane enable (U8T).
    * @param Register data value (U32T).
    */
    U32T test31::readByteLanestest31_intf(U32T address, U8T BE)
    {
        // Initialise return value
        U32T retVal = 0;
        
        // Determine data mask
        U32T dataMask = 0;
        for (int i = 0; i < 4; i++)
        {
            if (((BE >> i) % 2) == 1)
            {
                dataMask |= (U32T)0xff << (i * 8);
            }
        }
        
        // test31_intfregname (in byte lanes 0 to 3)
        if ((address == (TEST31_INTF_REGNAME_ADDRESS & 0xfffffffc)) &&
        (((BE % 2) == 1) ||
        (((BE >> 1) % 2) == 1) ||
        (((BE >> 2) % 2) == 1) ||
        (((BE >> 3) % 2) == 1)))
        {
            retVal |= (U32T)(readtest31_intfregname() & (U32T)dataMask);
        }
        
        return retVal;
    }
    
    /**
    * Read access function for test31 component.
    * @param Register address value (U32T).
    * @param Transaction port (transactionPortType).
    * @param Register data value (U32T).
    */
    U32T test31::read(transactionPortType transactionPort, U32T address)
    {
        // Initialise return value
        U32T retVal = 0;
        switch (transactionPort)
        {
            // test31_intf
            case test31_INTF_TRANSACTION_PORT:
            retVal = readtest31_intf(address);
            break;
            // Default
            default:
            break;
        }
        return retVal;
    }
    
} // namespace DUOLOG
