/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
** created by        :
** generated by      : Agnisys
** generated from    : D:\AgnisysProjects\git_test\Allegro_test\Test\test31.idsng
** IDesignSpec rev   : idsbatch v4.16.26.2

***** This code is generated with following settings ***
**---------------------------------------------------------------------------------------------------------------*/


#ifndef __TEST31_REGISTERS_H
#define __TEST31_REGISTERS_H

#include "Access.h"
#include "Bitfield.h"
#include "Register.h"

namespace DUOLOG
{
    
    
    /*****************************************************************************/
    
    /**
    * regname class
    * This class represents the regname register within the test31 IP Block.
    */
    class regname
    {
        private:
        // ------------------------------------------------------------------------
        // Private member variables
        // ------------------------------------------------------------------------
        // Pointer to regname Register object
        Register<U32T> * m_register;
        // Pointer to f Bitfield object
        Bitfield<U32T> * m_bf f ;
        // Pointer to f2 Bitfield object
        Bitfield<U32T> * m_bf f2 ;
        
        public:
        // ------------------------------------------------------------------------
        // Public member variables
        // ------------------------------------------------------------------------
        // Class constructor
        regname();
        // Returns pointer to regname Register object
        Register<U32T> * getRegister();
        // Returns pointer to f Bitfield object
        Bitfield<U32T> * get f ();
        // Returns pointer to f2 Bitfield object
        Bitfield<U32T> * get f2 ();
    };
    
    
} //namespace DUOLOG

#endif /* __TEST31_REGISTERS_H */
