/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
** created by        :
** generated by      : Agnisys
** generated from    : D:\AgnisysProjects\git_test\Allegro_test\Test\test7.idsng
** IDesignSpec rev   : idsbatch v4.16.26.2

***** This code is generated with following settings ***
**---------------------------------------------------------------------------------------------------------------*/


#ifndef __TEST7_H
#define __TEST7_H

#include "Access.h"
#include "test7Registers.h"
#include "LocatedRegister.h"

namespace DUOLOG
{
    
    class test7
    {
        private:
        // ------------------------------------------------------------------------
        // Private member variables
        // ------------------------------------------------------------------------
        regname1 * m_regregname1;
        // Pointer to LocatedRegister object representing regname1 at address 0x000
        LocatedRegister<U32T> * m_loctest7_intfregname1;
        // ------------------------------------------------------------------------
        // Private member variables
        // ------------------------------------------------------------------------
        // Creates register objects
        void createRegisters();
        // Creates memory objects
        void createMemories();
        // Locates registers
        void locateRegisters();
        // Locates memories
        void locateMemories();
        
        public:
        // ------------------------------------------------------------------------
        // Public member variables
        // ------------------------------------------------------------------------
        // regname1 register offset address definition(s)
        static const U32T TEST7_INTF_REGNAME1_ADDRESS = 0x000;
        
        
        
        
        // test7 transaction port enumerations
        enum transactionPortType {
        test7_INTF_TRANSACTION_PORT
    };
    // ------------------------------------------------------------------------
    // Public member functions
    // ------------------------------------------------------------------------
    // Class constructor
    test7();
    // Initialises all registers in the component
    void initialise();
    // Returns a pointer to the regname1 object representing regname1
    regname1 * getregname1();
    // Returns pointer to LocatedRegister object representing regname1 at address 0x000
    LocatedRegister<U32T> * gettest7_intfregname1();
    // Write access function for regname1 at address 0x000
    void  writetest7_intfregname1(U32T  data, U32T dataMask);
    // Write access function for test7 component test7_intf transaction target
    void  writetest7_intf(U32T  address, U32T data, U32T dataMask);
    // Write byte lanes access function for test7 component test7_intf transaction target
    void  writeByteLanestest7_intf(U32T  address, U8T BE, U32T data);
    // Write access function for component
    void  write (transactionPortType transactionPort, U32T  address, U32T data, U32T dataMask);
    // Read access function for regname1 at address 0x000
    U32T readtest7_intfregname1();
    // Read access function for test7 component test7_intf transaction target
    U32T readtest7_intf(U32T  address);
    // Read byte lanes access function for test7 component test7_intf transaction target
    U32T readByteLanestest7_intf(U32T  address, U8T BE);
    // Read access function for component
    U32T read(transactionPortType transactionPort, U32T  address);
};

} // namespace DUOLOG
#endif /* __CTT_H */
