//Allegro Microsystems LLC ***** Copyright 2017 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created by        :
// generated by      : Saurabh
// generated from    : F:\testGit\git_test\Sample467\test514\163001_AutoHdlPath.idsng
// IDesignSpec rev   : idsbatch v 6.16.4.7

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 32
// C++ Types int              : hwint
// Bus Type                   : PROPRIETARY
// BigEndian                  : true
// LittleEndian               : true
// Dist. Decode and Readback  : false
//---------------------------------------------------------------------------------------------------------------

`ifndef REG_MAP_REGMEM
`define REG_MAP_REGMEM

package reg_map_regmem_pkg;
    import uvm_pkg::*;
    `include "uvm_macros.svh"

    `include "reg_map.regmem.sv"

endpackage
`endif
