/*Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. ******/
/**/
/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ****/
/* created by        : */
/* generated by      : Saurabh*/
/* generated from    : C:\Users\Anupam\Documents\GitHub\git_test\Allegro_test\test_import\test88.idsng*/
/* IDesignSpec rev   : idsbatch v4.16.26.2*/

/**** This code is generated with following settings ****/
/* Reg Width                  : 32*/
/* Address Unit               : 8*/
/* C++ Types int              : hwint*/
/* Bus Type                   : PROPRIETARY*/
/* BigEndian                  : false*/
/* LittleEndian               : false*/
/* Dist. Decode and Readback  : false*/
/*--------------------------------------------------------------------------------------------------------------- */

/*block : b1 */

#ifndef _B1_REGS_H_
#define _B1_REGS_H_

typedef union {
    struct {
        hwint f1 : 16;           /* 0:15 SW=rw HW=rw 0x0 */
    } bf;
    hwint  w;
    
    
} b1_rg1;

typedef struct {
    b1_rg1  rg1;
    
    
    
} b1_s;


#define b1_s_SIZE 0x2
#define b1_rg1_SIZE 0x2

#define b1_s_OFFSET 0x0
#define b1_rg1_OFFSET 0x0

#define b1_s_ADDRESS 0x0
#define b1_rg1_ADDRESS 0x0
#define B1_RG1_F1_OFFSET 0  /* F1 DESCRIPTION :theeoxygen  */
#define B1_RG1_F1_MASK 0xFFFF
#endif /* _B1_REGS_H_ */

/* end */
