/**** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
** created by        :
** generated by      : Agnisys
** generated from    : D:\AgnisysProjects\git_test\Allegro_test\Merger\merg4.idsng
** IDesignSpec rev   : idsbatch v4.16.26.2

***** This code is generated with following settings ***
**---------------------------------------------------------------------------------------------------------------*/


#ifndef __MERG45_REGISTERS_H
#define __MERG45_REGISTERS_H

#include "Access.h"
#include "Bitfield.h"
#include "Register.h"

namespace DUOLOG
{
    
    
    /*****************************************************************************/
    
    /**
    * regnam class
    * This class represents the regnam register within the merg45 IP Block.
    */
    class regnam
    {
        private:
        // ------------------------------------------------------------------------
        // Private member variables
        // ------------------------------------------------------------------------
        // Pointer to regnam Register object
        Register<U32T> * m_register;
        // Pointer to ff Bitfield object
        Bitfield<U32T> * m_bf ff ;
        // Pointer to fxy Bitfield object
        Bitfield<U32T> * m_bf fxy ;
        // Pointer to fx1 Bitfield object
        Bitfield<U32T> * m_bf fx1 ;
        
        public:
        // ------------------------------------------------------------------------
        // Public member variables
        // ------------------------------------------------------------------------
        // Class constructor
        regnam();
        // Returns pointer to regnam Register object
        Register<U32T> * getRegister();
        // Returns pointer to ff Bitfield object
        Bitfield<U32T> * get ff ();
        // Returns pointer to fxy Bitfield object
        Bitfield<U32T> * get fxy ();
        // Returns pointer to fx1 Bitfield object
        Bitfield<U32T> * get fx1 ();
    };
    
    /*****************************************************************************/
    
    /**
    * regname2 class
    * This class represents the regname2 register within the merg45 IP Block.
    */
    class regname2
    {
        private:
        // ------------------------------------------------------------------------
        // Private member variables
        // ------------------------------------------------------------------------
        // Pointer to regname2 Register object
        Register<U8T> * m_register;
        // Pointer to f12 Bitfield object
        Bitfield<U8T> * m_bf f12 ;
        // Pointer to f1 Bitfield object
        Bitfield<U8T> * m_bf f1 ;
        // Pointer to f13 Bitfield object
        Bitfield<U8T> * m_bf f13 ;
        // Pointer to f11 Bitfield object
        Bitfield<U8T> * m_bf f11 ;
        
        public:
        // ------------------------------------------------------------------------
        // Public member variables
        // ------------------------------------------------------------------------
        // Class constructor
        regname2();
        // Returns pointer to regname2 Register object
        Register<U8T> * getRegister();
        // Returns pointer to f12 Bitfield object
        Bitfield<U8T> * get f12 ();
        // Returns pointer to f1 Bitfield object
        Bitfield<U8T> * get f1 ();
        // Returns pointer to f13 Bitfield object
        Bitfield<U8T> * get f13 ();
        // Returns pointer to f11 Bitfield object
        Bitfield<U8T> * get f11 ();
    };
    
    
} //namespace DUOLOG

#endif /* __MERG45_REGISTERS_H */
