//Agnisys, Inc. ***** Copyright 2018 All Rights Reserved. *****
//
//*** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
// created by        : 
// generated by      : Admin
// generated from    : C:\Users\Admin\Documents\GitHub\git_test\Allegro_test\case1\case1.idsng
// IDesignSpec rev   : idsbatch v4.16.26.2

//*** This code is generated with following settings ***
// Reg Width                  : 32
// Address Unit               : 8
// C++ Types int              : hwint
// Bus Type                   : AXI
// BigEndian                  : false
// LittleEndian               : false
// Dist. Decode and Readback  : false
//--------------------------------------------------------------------------------------------------------------- 
class chip_name_hw_agent extends uvm_agent;
    `uvm_component_utils(chip_name_hw_agent)

    chip_name_hw_driver hwdriver;
    chip_name_hw_monitor hwmonitor;
    uvm_sequencer #(hw_txn) hw_seqr;
    uvm_analysis_port #(hw_txn) hw_mon_ap;

    function new(string name, uvm_component parent);
        super.new(name,parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);

        hwdriver = chip_name_hw_driver::type_id::create("hwdriver",this);
        hwmonitor = chip_name_hw_monitor::type_id::create("hwmonitor",this);

        hw_seqr = new("hw_seqr",this);
        hw_mon_ap = new("hw_mon_ap",this);

        uvm_config_db #(uvm_sequencer#(hw_txn))::set(null,"*","hw_seqr",hw_seqr);
    endfunction

    function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);

        hwdriver.seq_item_port.connect(hw_seqr.seq_item_export);
        hwmonitor.mon_port.connect(this.hw_mon_ap);

    endfunction

endclass  : chip_name_hw_agent
