//=====================================================================================================================
//All Rights Reserved.
//*** This file is auto generated by ISequenceSpec (http://www.agnisys.com) . Please do not edit this file. ***
//Created by        :
//Generated by      : Saurabh
//Generated from    : C:\Users\Anupam\Documents\GitHub\git_test\Allegro_test\test_import\test88.idsng
//IDesignSpec rev   : idsbatch v4.16.26.2
//=====================================================================================================================


#include <stdbool.h>


void seq_name( ) {
    
    
}
